spring:
  application:
    name: turbine
server:
  port: 4001
management:
  server:
    port: 4002
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost/1001/eureka/
turbine:
  app-config: eurekaconsumerribbonhystrix
  cluster-name-expression: "default"
  combine-host-port: true