server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KeyGin/spring-cloud-demo
          basedir: target/config
          search-paths: config-repo
  application:
    name: configserver
  config:
    name: configserver