server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file://E://my-config-repo
          basedir: target/config
  application:
    name: configserver
  config:
    name: configserver